from .player import PlayerView
from .player_currently_playing import PlayerCurrentlyPlayingView
from .player_devices import PlayerDevices
from .player_next import PlayerSkipToNextView
from .player_pause import PlayerPausePlaybackView
from .player_play import PlayerStartResumePlayback
from .player_previous import PlayerSkipToPreviousView
from .player_queue import PlayerQueueView
from .player_recently_played import PlayerRecentlyPlayedView
from .player_repeat import PlayerRepeatView
from .player_seek import PlayerSeekPositionView
from .player_shuffle import PlayerShuffleView
from .player_volume import PlayerVolumeView
